### ISSUE TITLE
vue npm run build打包报错，到底是什么原因呀？

### ISSUE THREAD

**Issue by liuzhu7** [Tencent/weui#859]
ERROR in ./node_modules/css-loader!./node_modules/weui/dist/style/weui.css
Module build failed: TypeError: Cannot read property 'toFixed' of undefined
    at strongRound (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\plugins\convertPathData.js:766:21)
    at F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\plugins\convertPathData.js:424:17
    at Array.filter (<anonymous>)
    at filters (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\plugins\convertPathData.js:272:17)
    at Object.exports.fn (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\plugins\convertPathData.js:79:20)
    at F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\plugins.js:59:45
    at Array.filter (<anonymous>)
    at monkeys (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\plugins.js:66:17
    at Array.filter (<anonymous>)
    at monkeys (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\plugins.js:46:39)
    at perItem (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\plugins.js:77:12)
    at F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\plugins.js:18:24
    at Array.forEach (<anonymous>)
    at module.exports (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\plugins.js:14:13)
    at F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo.js:63:17
    at SAXParser.sax.onend (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\svg2js.js:156:13)
    at emit (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\sax\lib\sax.js:624:35)
    at end (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\sax\lib\sax.js:667:5)
    at SAXParser.write (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\sax\lib\sax.js:975:14)
    at SAXParser.close (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\sax\lib\sax.js:157:38)
    at module.exports (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo\svg2js.js:169:28)
    at module.exports.SVGO._optimizeOnce (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo.js:56:5)
    at module.exports.SVGO.optimize (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\svgo\lib\svgo.js:49:11)
    at F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\postcss-svgo\dist\index.js:64:25
    at new Promise (<anonymous>)
    at F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\postcss-svgo\dist\index.js:63:23
    at walk (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\postcss-value-parser\lib\walk.js:7:22)
    at ValueParser.walk (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\postcss-value-parser\lib\index.js:18:5)
    at minifyPromise (F:\SVNxm\qqdhua\web\mecwish-web2.0\node_modules\postcss-svgo\dist\index.js:33:64)
 @ ./node_modules/weui/dist/style/weui.css 4:14-66
 @ ./src/main.js
 @ multi babel-polyfill ./src/main.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! mecwish-web@1.0.0 build: `cross-env NODE_ENV=production webpack --progress --hide-modules`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the mecwish-web@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\admin\AppData\Roaming\npm-cache\_logs\2020-07-08T09_12_20_602Z-debug.log

**Comment by kxg916361108** [comment]
我也遇到了，请问你解决了吗

**Comment by 932370125** [comment]
我也遇到同样的问题，请问解决了吗
